### ISSUE TITLE
Code of JDBC_CONNECTION_STRING can not work well for MySQL8's jdbc url

### ISSUE THREAD

**Issue by FULaBUla** [SeunMatt/mysql-backup4j#14]
# Problem
Cause the jdbc url of MySql8 sometimes is like `"jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai"`  

at `MysqlExportService.java:385` `database = jdbcURL.substring(jdbcURL.lastIndexOf("/") + 1, jdbcURL.indexOf("?"));`， the value of `jdbcURL.lastIndexOf("/")` is larger than the value of `jdbcURL.indexOf("?")`,then it will cause `String index out of range`

**Comment by ayoub96anbara** [comment]
I think that the name of database is always after **the third "/"**,  so we can always search the index of the third "/" then we will start substring url from it.
`     
  String jdbcURL = "jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai";

       if (jdbcURL.contains("?")) {
            int index = jdbcURL.indexOf("/");
            for (int i = 0; i < 2; i++) {
                index = jdbcURL.indexOf("/", index + 1);
            }
            String database = jdbcURL.substring(index + 1, jdbcURL.indexOf("?"));
           }
`

**Comment by SeunMatt** [comment]
@FULaBUla This has been fixed in version 1.2.1. It will be available on Maven central in a couple of hours
