### ISSUE TITLE
sometimes can export Blob data but cannot import them 

### ISSUE THREAD

**Issue by FULaBUla** [SeunMatt/mysql-backup4j#16]
# problem
I using Blob/TinyBlob/MediumBlob in MySql8. Sometimes i can export data from database but i cannot import them when read Blod data from file, java.sql will throw exception because MysqlExportService.java_Line:258 will convert binary data to string and some strange characters in the string which will cause the subscripts to cross the bounds.

I think we need to add judgment sentence when the type is LONGVARBINARY and save data like 0x00001abc maybe can solve this problem

**Comment by SeunMatt** [comment]
Please provide code example of how you normally insert the blob data into the database and how you use them once they're pulled out of the database.

Given that Blob data are hexadecimally encoded before saving into the database, the getString function should work seamlessly. Please provide more info to help with this

**Comment by SeunMatt** [comment]
Issue fixed in version 1.3.0
