### ISSUE TITLE
java.sql.BatchUpdateException: Not a valid escape sequence

### ISSUE THREAD

**Issue by ypkkhatri** [SeunMatt/mysql-backup4j#20]
I have some java object in database, and export works fine but on import I'm getting an error:
```
Exception in thread "main" java.sql.BatchUpdateException: Not a valid escape sequence: {DÊû>
°²Ë?<sTXKC«Ì±0b?²7áý|!Àkn¢¾;7¥Gó?µF+?s§Â­ô?_nÇ¥?2Í?vsÃ¬ÃíâO*
```

**Comment by FULaBUla** [comment]
is it a blob data?

**Comment by ypkkhatri** [comment]
Yes thats right

**Comment by FULaBUla** [comment]
> Yes thats right

the PR #16 maybe resolve this problem.
i have same problem

**Comment by ypkkhatri** [comment]
Will it be merged?

**Comment by ypkkhatri** [comment]
@FULaBUla I have tried your PR and it worked for me.

**Comment by ypkkhatri** [comment]
As this issue will be resolved in #16 so closing this one.

**Comment by FULaBUla** [comment]
> Will it be merged?

I don't know, I have waited 1 week. o(╥﹏╥)o

**Comment by SeunMatt** [comment]
Hello @ypkkhatri please see this comment and respond. Thank you

**Comment by ypkkhatri** [comment]
Hi, sorry I'm not actually using the package anymore.
