### ISSUE TITLE
Not able to configure additional SMTP properties

### ISSUE THREAD

**Issue by sgroh** [SeunMatt/mysql-backup4j#22]
EmailService receive some properties like mail.smtp.auth, mail.smtp.starttls.enable, mail.smtp.host, mail.smtp.port, mail.smtp.ssl.trust but is not possible to setup neither mail.smtp.ssl.protocols nor mail.smtp.starttls.required.

**Comment by sgroh** [comment]
@SeunMatt I´ve created a PR to fix this.
https://github.com/SeunMatt/mysql-backup4j/pull/23

**Comment by SeunMatt** [comment]
Code changes present in version 1.3.0
