### ISSUE TITLE
clearTempFiles(false) not available anymore in version 1.2.1 wich is the latest.

### ISSUE THREAD

**Issue by albilu** [SeunMatt/mysql-backup4j#34]
> This is already possible. Set the property `MysqlExportService.PRESERVE_GENERATED_ZIP` to `true`.
> 
> ```
> //...
> properties.setProperty(MysqlExportService.PRESERVE_GENERATED_ZIP, "true");
> MysqlExportService mysqlExportService = new MysqlExportService(properties);
> mysqlExportService.export();
> File file = mysqlExportService.getGeneratedZipFile();
> ```
> 
> You can read more about it here https://smattme.com/posts/how-to-backup-mysql-database-programmatically-using-mysql-backup4j/

This is not available anymore in version 1.2.1 wich is the latest.

You can verify from the master branch also the method doesnt take any parameter: https://github.com/SeunMatt/mysql-backup4j/blob/master/src/main/java/com/smattme/MysqlExportService.java#L469

From the link you provided the boolean parameter was indeed supported for 1.0.1

Was there any reason to remove it? Otherwise it is a regression and you might want to add it back

_Originally posted by @albilu in https://github.com/SeunMatt/mysql-backup4j/issues/33#issuecomment-1742166033_

**Comment by SeunMatt** [comment]
If you look at the implementation of the `cleanTempFiles()` it takes the properties into account. https://github.com/SeunMatt/mysql-backup4j/blob/master/src/main/java/com/smattme/MysqlExportService.java#L469.

The onus will now be on you to delete the temp files yourself once you're done. This is achievable since you would have
configured the TEMP DIR in the first place: `properties.setProperty(MysqlExportService.TEMP_DIR, new File("external").getPath());`

Let me know if there's a need for any further clarifications.

The solution still remains to set the properties and use the getters to get the zip file and/or the SQL files.

**Comment by SeunMatt** [comment]
The important thing here is you need to first try it as described and also consider the function carefully

**Comment by albilu** [comment]
> The important thing here is you need to first try it as described and also consider the function carefully

@SeunMatt  I tried already it doesn't work!! 

clearTempFiles() check PRESERVE_GENERATED_ZIP if true(wich is needed to preserve the file while creating the instance) it doesn't delete 

else it delete right at the end of export()!

clearTempFiles(false) would work but as said it is not available in 1.2.1

My implementation is the same as the link you shared. Except i am using 1.2.1 not 1.0.1. 

It doesn't work! 

Anyway

**Comment by SeunMatt** [comment]
Please share a complete sample code and let me take a look at it.

**Comment by albilu** [comment]
This is the code:
```pom
<dependency>
    <groupId>com.smattme</groupId>
    <artifactId>mysql-backup4j</artifactId>
    <version>1.2.1</version>
</dependency>
```

```java
Properties properties = new Properties();

properties.setProperty(MysqlExportService.DB_NAME, dbName.split("/")[dbName.split("/").length - 1]);
properties.setProperty(MysqlExportService.DB_USERNAME, dbUserName);
properties.setProperty(MysqlExportService.DB_PASSWORD, dbPass);

properties.setProperty(MysqlExportService.TEMP_DIR, Files
        .createTempDirectory("mysql_backup").toString());

properties.setProperty(MysqlExportService.PRESERVE_GENERATED_ZIP, "true");


MysqlExportService mysqlExportService = new MysqlExportService(properties);

mysqlExportService.export();

File generatedZipFile = mysqlExportService.getGeneratedZipFile();

//Writing to a sftp session
try {
    session.write(new FileInputStream(generatedZipFile), "backupFile");
catch(Exception e) {
}

//This is not working. Files are not deleted
mysqlExportService.clearTempFiles();

```

**Comment by SeunMatt** [comment]
Hello @albilu,

Now I understand the challenge. 

Here is what you should do instead of calling `mysqlExportService.clearTempFiles();`

```
//save the temp path to a variable
Path mysqlBackupPath = Files.createTempDirectory("mysql_backup");
        
//use the variable in the temp_dir
properties.setProperty(MysqlExportService.TEMP_DIR, mysqlBackupPath.toString());
        
//once you're done, delete the file
Files.deleteIfExists(mysqlBackupPath);
```

**Comment by albilu** [comment]
> Hello @albilu,
> 
> Now I understand the challenge.
> 
> Here is what you should do instead of calling `mysqlExportService.clearTempFiles();`
> 
> ```
> //save the temp path to a variable
> Path mysqlBackupPath = Files.createTempDirectory("mysql_backup");
>         
> //use the variable in the temp_dir
> properties.setProperty(MysqlExportService.TEMP_DIR, mysqlBackupPath.toString());
>         
> //once you're done, delete the file
> Files.deleteIfExists(mysqlBackupPath);
> ```

the mysqlExportService.clearTempFiles(false); is the perfect solution. Why it was removed? 
More over as i said before it is more flexible to let the user decide whether or not the files should be deleted at the end of the export(so not calling clearTempFiles() in the export method)

Thanks for your feedbacks
