### ISSUE TITLE
Reimporting a single mysql table containing a longblob column throws exceptions

### ISSUE THREAD

**Issue by wolframwelschinger** [SeunMatt/mysql-backup4j#35]
I created a MySQL database containing a single table with a primary key column, some describing meta data columns and a longblob column. Then I added 3 records containing the meta data. Finally I used MySQL Workbench to upload the images by using its "Load Value From File..." function. Using the MySQL Workbench Value Editor I was able to display the Images correctly. After that I used the MysqlBackup4JIntegrationTest class to verify both export and import of the database. While export ran without complications the import threw exceptions.

I noticed the recommendation to store the images hexadecimally encoded but I have to handle a customer database in which all blobs are already filled up. So I tried to setup my test database nearly the same way like the customer did it.

Hope you can help me by solving the issue. 

Perhaps in MysqlExportService the method getDataInsertStatement should should handle blobs as hexadecimally encoded byte arrays rather than handle them as strings?

Here I uploaded my sample dump:

[mysqlbackup4j.dump.zip](https://github.com/SeunMatt/mysql-backup4j/files/14821703/mysqlbackup4j.dump.zip)

**Comment by SeunMatt** [comment]
Issue fixed in version 1.3.0. Please test and provide feedback

**Comment by wolframwelschinger** [comment]
Hello Seun,

I was surprised to receive your mail today. So it checked out your fixed version 1.3.0. as fast as I could when I was home.  Exporting tables containing longblob columns and then importing them to another schema doesn’t cause issues anymore. So I would like to thank you very much. 

Best regards!

Wolfram
