### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xul0038** [SeunMatt/mysql-backup4j#4]
bug：
connection = MysqlBaseService.connectWithURL(username, **username**,
			jdbcConnString, jdbcDriver);

**Comment by SeunMatt** [comment]
Thanks, this has been fixed in the master branch. Just that it has not been released pending other updates as well.

**Comment by fjosep** [comment]
Hello @SeunMatt - Any updates on when this fix will be rolled out? I see that the issue had been closed long back but I had the dependency added very recently to the project and it seems that the bug has not been fixed/the fix is not rolled out yet.  Thanks !

**Comment by SeunMatt** [comment]
Hi @fjosep 
The issue has been fixed, did you use the latest version - 1.0.1?
Please update the version and perhaps you're still having the issue, please don't hesitate to let me know. 

Cheers

**Comment by fjosep** [comment]
Hey @SeunMatt - I was at version 1.0.0 (from your blog & probably I didnt check the update link). 
After updating to new version 1.0.1 the issue got resolved. 

Thanks !

**Comment by SeunMatt** [comment]
Hi @fjosep 
Thanks for mentioning the blog post! I've updated the version there as well
