### ISSUE TITLE
Support of Remote Host

### ISSUE THREAD

**Issue by mossaab0** [SeunMatt/mysql-backup4j#6]
It appears that this works only when the DB is in `loclahost`.

**Comment by SeunMatt** [comment]
Hello, @mossaab0 kindly provide more information regarding this.
Provide code snippet as well. 
What did you do or try?
Did you get any errors? If yes please state them here.
Also, do you know you can set the connection string with a property?

```
properties.setProperty(MysqlExportService.JDBC_CONNECTION_STRING, "jdbc:mysql://localhost:3306/mnetsms_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false");
```

If you're using a remote connection string, then ensure the remote host is allowing connections remotely. Mysql doesn't by default. So you might want to look into that area.

Cheers.
